// utils/rolePermissions.js

const { PERMISSIONS } = require("./permissions");
const { ROLES } = require("./roles");

const ROLE_PERMISSIONS = {
  [ROLES.GLOBAL_ADMIN]: [
    PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    PERMISSIONS.VIEW_REGIONAL_TRANSACTIONS,
    PERMISSIONS.SUBMIT_TRANSACTIONS,
    PERMISSIONS.APPROVE_TRANSACTIONS,
    PERMISSIONS.REJECT_TRANSACTIONS,
    PERMISSIONS.FLAG_TRANSACTIONS,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_CONVERSION_RATES,
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.ACTIVATE_USERS,
    PERMISSIONS.DEACTIVATE_USERS,
  ],
  [ROLES.REGIONAL_ADMIN]: [
    PERMISSIONS.VIEW_REGIONAL_TRANSACTIONS,
    PERMISSIONS.APPROVE_TRANSACTIONS,
    PERMISSIONS.REJECT_TRANSACTIONS,
    PERMISSIONS.FLAG_TRANSACTIONS,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.VIEW_CONVERSION_RATES,
    PERMISSIONS.CREATE_USERS,

  ],
  [ROLES.SENDING_PARTNER]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.SUBMIT_TRANSACTIONS,
    PERMISSIONS.VIEW_CONVERSION_RATES,
    PERMISSIONS.VIEW_REQUESTS_ISENT,
    PERMISSIONS.CREATE_USERS,

  ],
  [ROLES.RECEIVING_PARTNER]: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.APPROVE_TRANSACTIONS,
    PERMISSIONS.REJECT_TRANSACTIONS,
    PERMISSIONS.FLAG_TRANSACTIONS,
    PERMISSIONS.VIEW_CONVERSION_RATES,
    PERMISSIONS.VIEW_REQUESTS_IRECEIVED,
  ],
};

module.exports = { ROLE_PERMISSIONS };
